spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
    - oauth
    - s3
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver


    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: off

server:
  servlet:
    session:
      timeout: 60s
  port: 80

token:
  secret: VMOYV9AlhmyO8quHcWwJUE3dEa2RblfL7QZW4GYzaNZo061ZiEJ8kx8ZWuvlC6Jcj # 64바이트 이상의 문자열
  access-token-expiration-time: 900000  # 15분 100000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

api:
  prefix: /api/v1
